# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Repositories overview
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.plugin.repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: forhearts
          base: repositories, metadata
          plugin_traffic: yes
          plugin_traffic_skipped: .github, home-page
      - name: 
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.plugin.repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: forhearts
          base: repositories
          plugin_traffic: yes
          plugin_traffic_skipped: .github
